export const Icon = {
  LogoPrimer: require("../Assets/icon/logo.svg").default,
  LogoPrimer2: require("../Assets/icon/logo.png"),
  CrossIcon: require("../Assets/icon/CrossIcon.png"),
  Call_Logo: require("../Assets/icon/Call.png"),
  Email_Logo: require("../Assets/icon/Email.png"),
  Location_Logo: require("../Assets/icon/Location.png"),
  FaceBook_Logo: require("../Assets/icon/FaceBook.svg").default,
  Instagram_Logo: require("../Assets/icon/Instagram.svg").default,
  linkedin_Logo: require("../Assets/icon/linkedin.svg").default,
  behance_Logo: require("../Assets/icon/behance.svg").default,
  link_Logo: require("../Assets/icon/link.svg").default,
  BackArrow: require("../Assets/icon/BackArrow.svg").default,
  IndianFlag: require("../Assets/icon/IndianFlag.svg").default,
  NextArrow: require("../Assets/icon/NextArrow.svg").default,
  Rocket: require("../Assets/icon/rocket.svg").default,
  RightArrow: require("../Assets/icon/RightArrow.svg").default,
  plusIcon: require("../Assets/icon/plusIcon.svg").default,
  DownArrow: require("../Assets/icon/DownArrow.svg").default,
  DownArrow2: require("../Assets/icon/DownArrow.png"),
  UpArrow: require("../Assets/icon/UpArrow.svg").default,
  ErrorInput_Logo: require("../Assets/icon/ErrorInput.svg").default,
};
